# Generated by Django 4.0.6 on 2022-07-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostpets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pet',
            new_name='missing_pet',
        ),
    ]
